title: Yaozheng Fang
position: Ph.D. Student
affiliation: College of Computer Science, Nankai University, CN.
email: fyz@mail.nankai.edu.cn
keywords: Blockchain, smart contract, computer arch
google_scholar: #
github_link: #
linkedin: #
avatar: ./assets/img/welcome.png
google_analytics: UA-111540567-4
favicon: ./assets/img/welcome.png
favicon_dark: ./assets/img/favicon-dark.png
description: Yaozheng Fang desc.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
